[versions]
agp = "8.13.2"
kotlin = "2.2.21"
kotlin-coroutines = "1.10.2"
ktor = "3.3.0"
arrow = "2.2.0"
kotest = "6.0.7"
kotest-arrow = "2.0.0"
# https://developer.android.com/jetpack/androidx/releases/compose
compose-bom = "2026.01.01"
compose = "1.9.1"
compose-material3 = "1.4.0"
activity-compose = "1.12.3"
lifecycle-viewmodel-compose = "2.10.0"
coil-compose = "2.7.0"
glance = "1.1.1"
hilt = "2.58"
room = "2.8.1"
androidx-work = "2.10.4"
hilt-work="1.3.0"
kotlinx-collections = "0.4.0"
paparazzi = "2.0.0-alpha05"
androidx-test-runner = "1.7.0"
androidx-test-ktx = "1.7.0"
androidx-test-ext = "1.3.0"
mockk = "1.14.5"
kotlinx-serialization-json = "1.9.0"
turbine = "1.2.1"
molecule = "2.2.0"
androidx-test-parameter-injector = "1.19"
# Android
min-sdk = "28"
compile-sdk = "36"
version-name = "2025.07.17"
version-code = "206"
jvm-target = "17"
# Linters
detekt = "1.23.8" # https://detekt.dev/docs/gettingstarted/gradle/
datastore = "1.1.7"
androidx-security = "1.1.0"
androidx-biometrics = "1.2.0-alpha05"
androidx-activity = "1.11.0"
appcompat-activity = "1.7.1"
androidx-recyclerview = "1.4.0"
material = "1.13.0"
timber = "5.0.1"
keval = "1.1.1"
opencsv-csv = "5.12.0"
opencsv-apache-commons = "3.18.0"
detekt-gradle-plugin = "1.23.8"
detekt-ruleset-compiler = "0.0.4"
detekt-ruleset-ktlint = "1.23.8"
detekt-ruleset-compose = "0.5.0"
google-play-services = "4.4.3"
google-play-update = "2.1.0"
google-play-services-tasks = "18.2.0"
google-play-review = "2.0.1"
firebase-crashlytics = "19.0.3"
firebase-crashlytics-gradle-plugin = "3.0.2"
firebase-firestore = "25.1.4"
ksp-plugin = "2.3.0"
module-graph-plugin = "2.6.0"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

# Kotlin
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-coroutines-googleplay-temp = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlin-coroutines" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections" }

# KotlinX Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

# Ktor
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

# Arrow
arrowkt-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }

# Testing
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-property-arrow = { module = "io.kotest.extensions:kotest-property-arrow", version.ref = "kotest-arrow" }
kotest-assertions-arrow = { module = "io.kotest.extensions:kotest-assertions-arrow", version.ref = "kotest-arrow" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
cashapp-molecule-runtime = { module = "app.cash.molecule:molecule-runtime", version.ref = "molecule" }
cashapp-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
paparazzi-plugin = { module = "app.cash.paparazzi:paparazzi-gradle-plugin", version.ref = "paparazzi" }
paparazzi = { module = "app.cash.paparazzi:paparazzi", version.ref = "paparazzi" }
google-testparameterinjector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "androidx-test-parameter-injector" }

# Integartion (Android) testing
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-core = { module = "androidx.test:core-ktx", version.ref = "androidx-test-ktx" }
androidx-test-ext = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

# Compose
compose-compiler-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-foundation = { module = "androidx.compose.foundation:foundation"}
compose-animation = { module = "androidx.compose.animation:animation"}
compose-tooling = { module = "androidx.compose.ui:ui-tooling"}
compose-runtime = { module = "androidx.compose.runtime:runtime"}
compose-ui = { module = "androidx.compose.ui:ui"}
compose-runtime-livedate-temp = { module = "androidx.compose.runtime:runtime-livedata"}
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended"}
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-material3-windowsize = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "compose-material3" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
glance = { module = "androidx.glance:glance", version.ref = "glance" }
glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }

# Room
room-plugin = { module = "androidx.room:androidx.room.gradle.plugin", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# Hilt
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }

# Google
google-services-plugin = { module = "com.google.gms:google-services", version.ref = "google-play-services" }
google-play-update = { module = "com.google.android.play:app-update", version.ref = "google-play-update" }
google-play-services = { module = "com.google.android.gms:play-services-tasks", version.ref = "google-play-services-tasks" }
google-play-review = { module = "com.google.android.play:review-ktx", version.ref = "google-play-review" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version = "19.0.3" }
firebase-crashlytics-gradle-plugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version = "3.0.2" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version = "25.1.4" }

# AndroidX
androidx-security = { module = "androidx.security:security-crypto", version.ref = "androidx-security" }
androidx-biometrics = { module = "androidx.biometric:biometric", version.ref = "androidx-biometrics" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
appcompat-activity = { module = "androidx.appcompat:appcompat", version.ref = "appcompat-activity" }
androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "androidx-work" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }

# Material
material = { module = "com.google.android.material:material", version.ref = "material" }

# Logging
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Legacy
keval = { module = "com.notkamui.libs:keval", version.ref = "keval" }
opencsv-csv = { module = "com.opencsv:opencsv", version.ref = "opencsv-csv" }
opencsv-apache-commons = { module = "org.apache.commons:commons-lang3", version.ref = "opencsv-apache-commons" }

# Linters
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-ruleset-compiler = { module = "com.braisgabin.detekt:kotlin-compiler-wrapper", version.ref = "detekt-ruleset-compiler" }
detekt-ruleset-ktlint = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-ruleset-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-ruleset-compose" }
detekt-ruleset-ivy-explicit = { module = "com.github.Ivy-Apps:detekt-explicit", version = "v0.0.8" }
slack-lint-compose = { module = "com.slack.lint.compose:compose-lint-checks", version = "1.3.1" }

# KSP
ksp-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp-plugin" }

# Modules Graph
module-graph-plugin = { module = "com.jraska.module.graph.assertion:plugin", version.ref = "module-graph-plugin" }


[bundles]
kotlin = [
    "kotlin-stdlib",
    "kotlin-coroutines-core",
    "kotlinx-collections-immutable"
]
kotlin-android = [
    "kotlin-coroutines-android",
    "kotlin-coroutines-googleplay-temp",
]
arrow = [
    "arrowkt-core",
]
ktor = [
    "kotlinx-serialization-json",
    "ktor-client-okhttp",
    "ktor-content-negotiation",
    "ktor-serialization",
    "ktor-client-core",
    "ktor-client-serialization",
    "ktor-logging",
]
testing = [
    "kotest-assertions",
    "kotest-property",
    "kotest-property-arrow",
    "kotest-assertions-arrow",
    "kotlin-coroutines-test",
    "mockk",
    "cashapp-turbine",
    "google-testparameterinjector"
]
integration-testing = [
    "kotest-assertions",
    "kotest-assertions-arrow",
    "kotlin-coroutines-test",
    "androidx-test-core",
    "androidx-test-runner",
    "androidx-test-ext"
]
compose = [
    "compose-animation",
    "compose-foundation",
    "compose-material3",
    "compose-material3-windowsize",
    "compose-material-icons-extended",
    "compose-runtime",
    "compose-ui",
    "compose-activity",
    "compose-viewmodel",
    "compose-tooling",
    "compose-runtime-livedate-temp",
    "compose-coil",
]
activity = [
    "androidx-activity",
    "appcompat-activity"
]
glance = [
    "glance",
    "glance-appwidget",
    "glance-material3"
]
google = [
    "google-play-update",
    "google-play-services",
    "google-play-review"
]
firebase = [
    "firebase-crashlytics"
]
hilt = [
    "hilt",
    "hilt-work"
]
room = [
    "room-runtime",
    "room-ktx"
]
opencsv = [
    "opencsv-csv",
    "opencsv-apache-commons"
]

[plugins]
gradleWrapperUpgrade = { id = "org.gradle.wrapper-upgrade", version = "0.11.4" }
koverPlugin = { id = "org.jetbrains.kotlinx.kover", version = "0.8.3" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose" }